### ISSUE TITLE
Please help to update Readme file

### ISSUE THREAD

**Issue by mcuee** [avrdudes/libhidapi#1]
I think it is better to update the Readme file to mention this is based on the official hidapi repo but with some changes. The Readme file is not really applicable.

**Comment by mcuee** [comment]
The other question is whether this fork is really needed or not, as the official HIDAPI project has moved on to use CMake.
https://github.com/libusb/hidapi

**Comment by mariusgreuel** [comment]
I added a README that described this purpose of this fork.
